In [7]:
import cnn_sts as cn

In [9]:
c = dict()
c['num_runs']   = 3
c['num_epochs'] = 64
c['num_batchs'] = 2
c['batch_size'] = 3000
c['wordvectdim']  = 300
c['sentencepad']  = 60
c['num_classes']  = 6
c['cnnfilters']     = {1: 1800}
c['cnninitial']     = 'he_uniform'
c['cnnactivate']    = 'relu'
c['densedimension'] = list([1800])
c['denseinitial']   = 'he_uniform'
c['denseactivate']  = 'tanh'
c['optimizer']  = 'adam'

In [10]:
tsk= cn.STSTask(c)

In [12]:
tsk.create_model()

inside convo: 
(?, 60, 300)
(?, 60, 300)
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
(?, 60, 1800)
(?, 60, 1800)
inside max
(?, 1, 1800)
(?, 1, 1800)
inside flat
(?, 1800)
(?, 1800)
(?, 1800)
(?, 3600)
inside dense
(?, 1800)
kd
(?, 6)


In [17]:
tsk.load_resc('glove.840B.300d.txt')


Loading GloVe...(This might take one or two minutes.)


In [18]:
tsk.load_data('sts-train.csv', 'sts-dev.csv', 'sts-test.csv')


counter 1
sl slice(0, 1379, None)
(1379,)
[Test]=[0.7664]


([0.7664],
 array([3.01930759, 4.38307604, 4.17335469, ..., 2.00090396, 2.14591413,
        2.10718082]))

In [23]:
tsk.model.load_weights('weightfile0')
l=tsk.eval_model1()

counter 1
sl slice(0, 1379, None)
(1379,)
[Test]=[0.7762]


In [24]:
l

([0.7762],
 array([3.54232341, 4.67332291, 4.18211007, ..., 1.62091905, 1.59009893,
        1.36366148]))

In [26]:
l[1].shape

(1379,)

In [1]:
import numpy as np

In [10]:
arr= np.random.randn(5,3)

In [12]:
arr

array([[-0.99653334, -1.68416886, -1.43351852],
       [ 0.90225156,  1.13908162, -1.12996816],
       [ 2.14821817,  0.56741721,  0.0212782 ],
       [ 0.24275738, -1.04373585, -0.28337288],
       [-1.57631183,  0.95838013,  0.2565694 ]])

In [13]:
a= np.random.randn(5)

In [14]:
a

array([-0.50974171,  0.27113209, -0.14515201,  0.87915781, -0.73611647])

In [26]:
a=a.reshape(5,1)
a.shape

(5, 1)

In [30]:
x=np.append(arr,a,axis=1)

In [1]:
x.shape

NameError: name 'x' is not defined